// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sistema_Bancario_Sprint3.Data;

#nullable disable

namespace Sistema_Bancario_Sprint3.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260526013801_SeedDadosIniciais")]
    partial class SeedDadosIniciais
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Sistema_Bancario_Sprint3.Models.Cliente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("TipoPessoa")
                        .HasColumnType("int");

                    b.Property<string>("cpfCnpj")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Clientes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 20L,
                            DataCadastro = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "joao@ubank.com",
                            Nome = "João Silva",
                            Telefone = "(81) 99999-0001",
                            TipoPessoa = 0,
                            cpfCnpj = "11111111111"
                        },
                        new
                        {
                            Id = 21L,
                            DataCadastro = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "maria@ubank.com",
                            Nome = "Maria Santos",
                            Telefone = "(81) 99999-0002",
                            TipoPessoa = 0,
                            cpfCnpj = "22222222222"
                        },
                        new
                        {
                            Id = 22L,
                            DataCadastro = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "empresa@ubank.com",
                            Nome = "Tech Empresa Ltda",
                            Telefone = "(81) 99999-0003",
                            TipoPessoa = 1,
                            cpfCnpj = "00000000000100"
                        });
                });

            modelBuilder.Entity("Sistema_Bancario_Sprint3.Models.Conta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Agencia")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)");

                    b.Property<string>("CnpjVinculado")
                        .HasMaxLength(14)
                        .HasColumnType("varchar(14)")
                        .HasColumnName("CnpjVinculado");

                    b.Property<DateTime>("DataAbertura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<int?>("DiaRendimento")
                        .HasColumnType("int")
                        .HasColumnName("DiaRendimento");

                    b.Property<long>("IdCliente")
                        .HasColumnType("bigint");

                    b.Property<long>("IdTipoConta")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("LimiteCredito")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NumeroConta")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)");

                    b.Property<decimal>("Saldo")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal?>("TaxaJuros")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdTipoConta");

                    b.ToTable("Contas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 20L,
                            Agencia = "0001",
                            DataAbertura = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdCliente = 20L,
                            IdTipoConta = 1L,
                            NumeroConta = "1001",
                            Saldo = 1000.00m,
                            Status = "ativa"
                        },
                        new
                        {
                            Id = 21L,
                            Agencia = "0001",
                            DataAbertura = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiaRendimento = 1,
                            IdCliente = 21L,
                            IdTipoConta = 2L,
                            NumeroConta = "2002",
                            Saldo = 2000.00m,
                            Status = "ativa",
                            TaxaJuros = 0.5m
                        },
                        new
                        {
                            Id = 22L,
                            Agencia = "0001",
                            CnpjVinculado = "00000000000100",
                            DataAbertura = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdCliente = 22L,
                            IdTipoConta = 3L,
                            LimiteCredito = 50000.00m,
                            NumeroConta = "3003",
                            Saldo = 5000.00m,
                            Status = "ativa"
                        });
                });

            modelBuilder.Entity("Sistema_Bancario_Sprint3.Models.TipoConta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Tipos_Contas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Nome = "Corrente"
                        },
                        new
                        {
                            Id = 2L,
                            Nome = "Poupança"
                        },
                        new
                        {
                            Id = 3L,
                            Nome = "Empresarial"
                        });
                });

            modelBuilder.Entity("Sistema_Bancario_Sprint3.Models.Transacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataHora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<long?>("IdContaDestino")
                        .HasColumnType("bigint");

                    b.Property<long>("IdContaOrigem")
                        .HasColumnType("bigint");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdContaDestino");

                    b.HasIndex("IdContaOrigem");

                    b.ToTable("Transacoes", (string)null);
                });

            modelBuilder.Entity("Sistema_Bancario_Sprint3.Models.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<long?>("IdCliente")
                        .HasColumnType("bigint");

                    b.Property<int>("Role")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IdCliente");

                    b.ToTable("Usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 20L,
                            DataCriacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "joao@ubank.com",
                            IdCliente = 20L,
                            Role = 0,
                            SenhaHash = "$2a$11$CS9lAe5X2fX61LBmblHaBOr13EN/CoeL8XnOzV.Fktv4goiPk3TOW",
                            Status = 1
                        },
                        new
                        {
                            Id = 21L,
                            DataCriacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "maria@ubank.com",
                            IdCliente = 21L,
                            Role = 0,
                            SenhaHash = "$2a$11$A0vx5bNNOPW3prMi1z0gku//A8214tcA2r2gAU2DSYV2wD4HeowgG",
                            Status = 1
                        },
                        new
                        {
                            Id = 22L,
                            DataCriacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "empresa@ubank.com",
                            IdCliente = 22L,
                            Role = 0,
                            SenhaHash = "$2a$11$mBvpGArj5rA1GE3n01y7quAvjIn1mvngvqUtKRrUVGOiUEjJlcja2",
                            Status = 1
                        });
                });

            modelBuilder.Entity("Sistema_Bancario_Sprint3.Models.Conta", b =>
                {
                    b.HasOne("Sistema_Bancario_Sprint3.Models.Cliente", "Cliente")
                        .WithMany("Contas")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_cliente");

                    b.HasOne("Sistema_Bancario_Sprint3.Models.TipoConta", "TipoConta")
                        .WithMany("Contas")
                        .HasForeignKey("IdTipoConta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_tipo_conta");

                    b.Navigation("Cliente");

                    b.Navigation("TipoConta");
                });

            modelBuilder.Entity("Sistema_Bancario_Sprint3.Models.Transacao", b =>
                {
                    b.HasOne("Sistema_Bancario_Sprint3.Models.Conta", "ContaDestino")
                        .WithMany()
                        .HasForeignKey("IdContaDestino")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_conta_destino");

                    b.HasOne("Sistema_Bancario_Sprint3.Models.Conta", "ContaOrigem")
                        .WithMany()
                        .HasForeignKey("IdContaOrigem")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_conta_origem");

                    b.Navigation("ContaDestino");

                    b.Navigation("ContaOrigem");
                });

            modelBuilder.Entity("Sistema_Bancario_Sprint3.Models.Usuario", b =>
                {
                    b.HasOne("Sistema_Bancario_Sprint3.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Usuario_Cliente");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Sistema_Bancario_Sprint3.Models.Cliente", b =>
                {
                    b.Navigation("Contas");
                });

            modelBuilder.Entity("Sistema_Bancario_Sprint3.Models.TipoConta", b =>
                {
                    b.Navigation("Contas");
                });
#pragma warning restore 612, 618
        }
    }
}
