// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sistema_Bancario_Sprint3.Data;

#nullable disable

namespace Sistema_Bancario_Sprint3.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260424195043_ImplementarTabelas")]
    partial class ImplementarTabelas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Sistema_Bancario_Sprint3.Models.Cliente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("cpfCnpj")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("tipoPessoa")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("Sistema_Bancario_Sprint3.Models.Conta", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Agencia")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)");

                    b.Property<DateTime>("DataAbertura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("IdCliente")
                        .HasColumnType("bigint");

                    b.Property<string>("NumeroConta")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)");

                    b.Property<decimal>("Saldo")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TipoConta")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Contas", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Sistema_Bancario_Sprint3.Models.Transacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataHora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long?>("FK_conta_destino")
                        .HasColumnType("bigint");

                    b.Property<long>("FK_conta_origem")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("FK_conta_destino");

                    b.HasIndex("FK_conta_origem");

                    b.ToTable("Transacoes", (string)null);
                });

            modelBuilder.Entity("Sistema_Bancario_Sprint3.Models.ContaCorrente", b =>
                {
                    b.HasBaseType("Sistema_Bancario_Sprint3.Models.Conta");

                    b.ToTable("Contas_Corrente", (string)null);
                });

            modelBuilder.Entity("Sistema_Bancario_Sprint3.Models.ContaEmpresarial", b =>
                {
                    b.HasBaseType("Sistema_Bancario_Sprint3.Models.Conta");

                    b.Property<string>("CpnjVinculado")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("varchar(14)");

                    b.Property<decimal>("limiteCredito")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable("Contas_Empresarial", (string)null);
                });

            modelBuilder.Entity("Sistema_Bancario_Sprint3.Models.ContaPoupanca", b =>
                {
                    b.HasBaseType("Sistema_Bancario_Sprint3.Models.Conta");

                    b.Property<int>("DiaRrendimento")
                        .HasColumnType("int");

                    b.Property<decimal>("TaxaJuros")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.ToTable("Contas_Poupanca", (string)null);
                });

            modelBuilder.Entity("Sistema_Bancario_Sprint3.Models.Conta", b =>
                {
                    b.HasOne("Sistema_Bancario_Sprint3.Models.Cliente", "Cliente")
                        .WithMany("Contas")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Sistema_Bancario_Sprint3.Models.Transacao", b =>
                {
                    b.HasOne("Sistema_Bancario_Sprint3.Models.Conta", "ContaDestino")
                        .WithMany()
                        .HasForeignKey("FK_conta_destino")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sistema_Bancario_Sprint3.Models.Conta", "ContaOrigem")
                        .WithMany()
                        .HasForeignKey("FK_conta_origem")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ContaDestino");

                    b.Navigation("ContaOrigem");
                });

            modelBuilder.Entity("Sistema_Bancario_Sprint3.Models.ContaCorrente", b =>
                {
                    b.HasOne("Sistema_Bancario_Sprint3.Models.Conta", null)
                        .WithOne()
                        .HasForeignKey("Sistema_Bancario_Sprint3.Models.ContaCorrente", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sistema_Bancario_Sprint3.Models.ContaEmpresarial", b =>
                {
                    b.HasOne("Sistema_Bancario_Sprint3.Models.Conta", null)
                        .WithOne()
                        .HasForeignKey("Sistema_Bancario_Sprint3.Models.ContaEmpresarial", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sistema_Bancario_Sprint3.Models.ContaPoupanca", b =>
                {
                    b.HasOne("Sistema_Bancario_Sprint3.Models.Conta", null)
                        .WithOne()
                        .HasForeignKey("Sistema_Bancario_Sprint3.Models.ContaPoupanca", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sistema_Bancario_Sprint3.Models.Cliente", b =>
                {
                    b.Navigation("Contas");
                });
#pragma warning restore 612, 618
        }
    }
}
